name: randevu_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  email_validator: ^3.0.0
  http: ^1.3.0
  intl: ^0.20.2
  multi_select_flutter: ^4.1.3
  geolocator: ^10.0.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  firebase_core: ^2.18.0
  cloud_firestore: ^4.15.1
  flutter_typeahead: ^4.1.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.1.0
  url_launcher: ^6.1.11
  universal_html: ^2.2.1
  flutter_animate: ^4.5.2
  iconsax: ^0.0.8
  table_calendar: ^3.2.0
  time_range: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Randevu_Logo.jpg
